///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package axi_checker_axi_vip_0_0_pkg;
import axi_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter axi_checker_axi_vip_0_0_VIP_PROTOCOL           = 0;
      parameter axi_checker_axi_vip_0_0_VIP_READ_WRITE_MODE    = "READ_WRITE";
      parameter axi_checker_axi_vip_0_0_VIP_INTERFACE_MODE     = 2;
      parameter axi_checker_axi_vip_0_0_VIP_ADDR_WIDTH         = 33;
      parameter axi_checker_axi_vip_0_0_VIP_DATA_WIDTH         = 256;
      parameter axi_checker_axi_vip_0_0_VIP_ID_WIDTH           = 6;
      parameter axi_checker_axi_vip_0_0_VIP_AWUSER_WIDTH       = 0;
      parameter axi_checker_axi_vip_0_0_VIP_ARUSER_WIDTH       = 0;
      parameter axi_checker_axi_vip_0_0_VIP_RUSER_WIDTH        = 0;
      parameter axi_checker_axi_vip_0_0_VIP_WUSER_WIDTH        = 0;
      parameter axi_checker_axi_vip_0_0_VIP_BUSER_WIDTH        = 0;
      parameter axi_checker_axi_vip_0_0_VIP_SUPPORTS_NARROW    = 1;
      parameter axi_checker_axi_vip_0_0_VIP_HAS_BURST          = 1;
      parameter axi_checker_axi_vip_0_0_VIP_HAS_LOCK           = 1;
      parameter axi_checker_axi_vip_0_0_VIP_HAS_CACHE          = 1;
      parameter axi_checker_axi_vip_0_0_VIP_HAS_REGION         = 1;
      parameter axi_checker_axi_vip_0_0_VIP_HAS_QOS            = 1;
      parameter axi_checker_axi_vip_0_0_VIP_HAS_PROT           = 1;
      parameter axi_checker_axi_vip_0_0_VIP_HAS_WSTRB          = 1;
      parameter axi_checker_axi_vip_0_0_VIP_HAS_BRESP          = 1;
      parameter axi_checker_axi_vip_0_0_VIP_HAS_RRESP          = 1;
      parameter axi_checker_axi_vip_0_0_VIP_HAS_ACLKEN         = 0;
      parameter axi_checker_axi_vip_0_0_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////


typedef axi_slv_agent #(axi_checker_axi_vip_0_0_VIP_PROTOCOL, 
                        axi_checker_axi_vip_0_0_VIP_ADDR_WIDTH,
                        axi_checker_axi_vip_0_0_VIP_DATA_WIDTH,
                        axi_checker_axi_vip_0_0_VIP_DATA_WIDTH,
                        axi_checker_axi_vip_0_0_VIP_ID_WIDTH,
                        axi_checker_axi_vip_0_0_VIP_ID_WIDTH,
                        axi_checker_axi_vip_0_0_VIP_AWUSER_WIDTH, 
                        axi_checker_axi_vip_0_0_VIP_WUSER_WIDTH, 
                        axi_checker_axi_vip_0_0_VIP_BUSER_WIDTH, 
                        axi_checker_axi_vip_0_0_VIP_ARUSER_WIDTH,
                        axi_checker_axi_vip_0_0_VIP_RUSER_WIDTH, 
                        axi_checker_axi_vip_0_0_VIP_SUPPORTS_NARROW, 
                        axi_checker_axi_vip_0_0_VIP_HAS_BURST,
                        axi_checker_axi_vip_0_0_VIP_HAS_LOCK,
                        axi_checker_axi_vip_0_0_VIP_HAS_CACHE,
                        axi_checker_axi_vip_0_0_VIP_HAS_REGION,
                        axi_checker_axi_vip_0_0_VIP_HAS_PROT,
                        axi_checker_axi_vip_0_0_VIP_HAS_QOS,
                        axi_checker_axi_vip_0_0_VIP_HAS_WSTRB,
                        axi_checker_axi_vip_0_0_VIP_HAS_BRESP,
                        axi_checker_axi_vip_0_0_VIP_HAS_RRESP,
                        axi_checker_axi_vip_0_0_VIP_HAS_ARESETN) axi_checker_axi_vip_0_0_slv_t;

typedef axi_slv_mem_agent #(axi_checker_axi_vip_0_0_VIP_PROTOCOL, 
                        axi_checker_axi_vip_0_0_VIP_ADDR_WIDTH,
                        axi_checker_axi_vip_0_0_VIP_DATA_WIDTH,
                        axi_checker_axi_vip_0_0_VIP_DATA_WIDTH,
                        axi_checker_axi_vip_0_0_VIP_ID_WIDTH,
                        axi_checker_axi_vip_0_0_VIP_ID_WIDTH,
                        axi_checker_axi_vip_0_0_VIP_AWUSER_WIDTH, 
                        axi_checker_axi_vip_0_0_VIP_WUSER_WIDTH, 
                        axi_checker_axi_vip_0_0_VIP_BUSER_WIDTH, 
                        axi_checker_axi_vip_0_0_VIP_ARUSER_WIDTH,
                        axi_checker_axi_vip_0_0_VIP_RUSER_WIDTH, 
                        axi_checker_axi_vip_0_0_VIP_SUPPORTS_NARROW, 
                        axi_checker_axi_vip_0_0_VIP_HAS_BURST,
                        axi_checker_axi_vip_0_0_VIP_HAS_LOCK,
                        axi_checker_axi_vip_0_0_VIP_HAS_CACHE,
                        axi_checker_axi_vip_0_0_VIP_HAS_REGION,
                        axi_checker_axi_vip_0_0_VIP_HAS_PROT,
                        axi_checker_axi_vip_0_0_VIP_HAS_QOS,
                        axi_checker_axi_vip_0_0_VIP_HAS_WSTRB,
                        axi_checker_axi_vip_0_0_VIP_HAS_BRESP,
                        axi_checker_axi_vip_0_0_VIP_HAS_RRESP,
                        axi_checker_axi_vip_0_0_VIP_HAS_ARESETN) axi_checker_axi_vip_0_0_slv_mem_t;
                        
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      axi_checker_axi_vip_0_0_slv_t  axi_checker_axi_vip_0_0_slv;
//      initial begin : START_axi_checker_axi_vip_0_0_SLAVE
//        axi_checker_axi_vip_0_0_slv = new("axi_checker_axi_vip_0_0_slv", `axi_checker_axi_vip_0_0_PATH_TO_INTERFACE);
//        axi_checker_axi_vip_0_0_slv.start_slave();
//      end

endpackage : axi_checker_axi_vip_0_0_pkg
